# -*- coding: utf-8 -*-
"""Patient Records Management System.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uKzLKH5eOYC0A0R0BXT0-Gv89GFVT1k2

# **Imports and Data Loading Function**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def load_records(file_path):
    """
    Standalone Function 1: Loads and cleans the patient data.
    - Handles missing values in the 'status' column.
    """
    try:
        df = pd.read_csv(file_path)
        # Handling missing values: Fill empty 'status' with 'Pending'
        df['status'] = df['status'].fillna('Pending')
        print(f"Successfully loaded {len(df)} records.")
        return df
    except FileNotFoundError:
        print("Error: The CSV file was not found.")
        return None

# Load the data
df_patients = load_records('02_patient_records.csv')

"""# **Defining Custom Classes (OOP)**"""

class Patient:
    """
    Custom Class 1: Represents an individual patient.
    """
    def __init__(self, patient_id, name, age, diagnosis, ward, status):
        self.patient_id = patient_id
        self.name = name
        self.age = age
        self.diagnosis = diagnosis
        self.ward = ward
        self.status = status

    def display_info(self):
        """Method 1: Displays patient details."""
        return f"ID: {self.patient_id} | Name: {self.name} | Age: {self.age} | Ward: {self.ward} | Status: {self.status}"

    def update_status(self, new_status):
        """Method 2: Updates the patient's current status."""
        self.status = new_status
        return f"Status for {self.name} updated to {new_status}."

class RecordsManager:
    """
    Custom Class 2: Manages a collection of Patient objects.
    """
    def __init__(self):
        self.patients_list = []

    def add_patient(self, patient_obj):
        """Method 1: Adds a Patient object to the registry."""
        self.patients_list.append(patient_obj)

    def get_summary_count(self):
        """Method 2: Returns the total number of patients managed."""
        return len(self.patients_list)

"""# **Search and Summary Functions**"""

def search_patient(manager, search_term):
    """
    Standalone Function 2: Searches for a patient by ID or Name.
    """
    results = [p.display_info() for p in manager.patients_list
               if search_term.lower() in p.name.lower() or search_term.upper() in p.patient_id]
    return results if results else ["No patient found matching that term."]

def generate_summary_stats(df):
    """
    Standalone Function 3: Generates summary statistics using Pandas.
    """
    print("\n--- Basic Summary Statistics ---")
    print(df[['age']].describe())

    print("\n--- Patients per Ward ---")
    print(df['ward'].value_counts())

    return df.groupby('diagnosis')['age'].mean() # Average age per diagnosis

"""# **Visualizations and Execution**"""

def create_visualizations(df):
    """
    Creates 3 mandatory charts using Matplotlib and Seaborn.
    """
    # Set the style
    sns.set_theme(style="whitegrid")

    # Chart 1: Age Distribution (Histogram)
    plt.figure(figsize=(10, 5))
    sns.histplot(df['age'], bins=12, kde=True, color='teal')
    plt.title('Patient Age Distribution')
    plt.xlabel('Age')
    plt.ylabel('Frequency')
    plt.show()

    # Chart 2: Ward Distribution (Bar Chart)
    plt.figure(figsize=(10, 5))
    df['ward'].value_counts().plot(kind='bar', color='salmon')
    plt.title('Patient Count by Ward')
    plt.xlabel('Ward Name')
    plt.ylabel('Number of Patients')
    plt.xticks(rotation=45)
    plt.show()

    # Chart 3: Diagnosis Breakdown (Pie Chart)
    plt.figure(figsize=(8, 8))
    df['diagnosis'].value_counts().plot(kind='pie', autopct='%1.1f%%', startangle=140)
    plt.title('Distribution of Diagnoses')
    plt.ylabel('')
    plt.show()

# --- EXECUTION ---
if df_patients is not None:
    # 1. Initialize the Manager and load Class Objects
    manager = RecordsManager()
    for index, row in df_patients.iterrows():
        p = Patient(row['patient_id'], row['name'], row['age'], row['diagnosis'], row['ward'], row['status'])
        manager.add_patient(p)

    # 2. Run Statistics
    avg_age_diag = generate_summary_stats(df_patients)

    # 3. Test Search Functionality
    print("\n--- Search Test (Patient 5) ---")
    print(search_patient(manager, "Patient 5"))

    # 4. Generate Charts
    create_visualizations(df_patients)