# -*- coding: utf-8 -*-
"""Patient Records Management System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nd2dnVTK7gnwkaKIaIXfwvvGE1N0b805
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- STANDALONE FUNCTIONS ---

def load_records(file_path):
    """Function 1: Loads and cleans data from CSV"""
    try:
        df = pd.read_csv(file_path)
        df['status'] = df['status'].fillna('Unknown') # Data cleaning
        print(f">>> Success: {len(df)} records loaded.")
        return df
    except Exception as e:
        print(f">>> Error loading CSV: {e}")
        return None

def generate_summary(df):
    """Function 2: Generates summary statistics"""
    print("\n--- DATABASE SUMMARY ---")
    print(f"Total Patients: {len(df)}")
    print(f"Average Age: {df['age'].mean():.1f} years")
    print("\nPatients per Ward:")
    print(df['ward'].value_counts())

# --- CLASSES ---

class Patient:
    """Class 1: Individual Patient Record"""
    def __init__(self, pid, name, gender, age, diagnosis, ward, status):
        self.pid = pid
        self.name = name
        self.gender = gender
        self.age = age
        self.diagnosis = diagnosis
        self.ward = ward
        self.status = status

    def __str__(self):
        return f"[{self.pid}] {self.name} | {self.gender} | Age: {self.age} | {self.diagnosis} | {self.ward} | Status: {self.status}"

class RecordsManager:
    """Class 2: Handles the database operations"""
    def __init__(self, dataframe):
        self.patients = []
        # Convert dataframe rows into Patient objects
        for _, row in dataframe.iterrows():
            p = Patient(row['patient_id'], row['name'], row['gender'],
                        row['age'], row['diagnosis'], row['ward'], row['status'])
            self.patients.append(p)

    def search_patient(self, term):
        """Method 1: Search by Name or ID"""
        results = [p for p in self.patients if term.lower() in p.name.lower() or term.upper() in p.pid]
        return results

    def filter_records(self, criteria, value):
        """Method 2: Filter by Gender or Ward"""
        if criteria == "gender":
            return [p for p in self.patients if p.gender.lower() == value.lower()]
        elif criteria == "ward":
            return [p for p in self.patients if p.ward.lower() == value.lower()]
        return []

# --- VISUALIZATION FUNCTION ---

def show_charts(df):
    """Function 3: Generates the 3 mandatory charts"""
    sns.set_theme(style="darkgrid")
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    # 1. Bar Chart (Diagnoses)
    sns.countplot(data=df, x='diagnosis', ax=axes[0], palette='viridis')
    axes[0].set_title('Patients per Diagnosis')
    axes[0].tick_params(axis='x', rotation=45)

    # 2. Histogram (Age Distribution)
    sns.histplot(df['age'], bins=10, kde=True, ax=axes[1], color='orange')
    axes[1].set_title('Age Distribution')

    # 3. Pie Chart (Gender Split)
    df['gender'].value_counts().plot(kind='pie', autopct='%1.1f%%', ax=axes[2], colors=['skyblue', 'lightpink'])
    axes[2].set_title('Gender Split')
    axes[2].set_ylabel('')

    plt.tight_layout()
    plt.show()

# --- MAIN INTERACTIVE LOOP ---

def main():
    df = load_records('02_patient_records.csv')
    if df is None: return

    manager = RecordsManager(df)

    while True:
        print("\n=== PATIENT RECORDS MANAGEMENT SYSTEM ===")
        print("1. View All Records")
        print("2. Search Patient (Name/ID)")
        print("3. Filter by Gender or Ward")
        print("4. Generate Summary Statistics")
        print("5. View Analytics Charts")
        print("6. Exit")

        choice = input("\nSelect an option (1-6): ")

        if choice == '1':
            for p in manager.patients[:10]: print(p) # Show first 10
            print(f"... and {len(manager.patients)-10} more.")

        elif choice == '2':
            term = input("Enter Name or Patient ID: ")
            results = manager.search_patient(term)
            for r in results: print(r)

        elif choice == '3':
            c = input("Filter by (gender/ward): ").lower()
            v = input(f"Enter {c} value: ")
            results = manager.filter_records(c, v)
            for r in results: print(r)

        elif choice == '4':
            generate_summary(df)

        elif choice == '5':
            show_charts(df)

        elif choice == '6':
            print("Exiting system. Goodbye!")
            break
        else:
            print("Invalid choice, try again.")

if __name__ == "__main__":
    main()